# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1db5eee16ff2841648b10b0293520fdcb340afb8230bff80259bf7e785db0319abd28a0ce4bb5ba12950472144400c25945a1d9868e65abb0de5cb310d4c934b

test:
  secret_key_base: 04ee9321fd87de09d21d1b0479548673d0e98e3346669f7fff143dbdb9aea871b5400fb3d38041d85a3f84de6c94be7dd33de45d9095a0ca862e9be8a36363c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
